name: 'Cloud Run w/ CloudSQL'
description: 'Authenticate with gcloud, push image to GCR and deploy as a new revision to Cloud Run, allow CloudSQL connection'
author: 'Nuttapat Koonarangsri'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
inputs:
  image:
    description: 'Name of the docker image'
    required: true
  service:
    description: 'Name of the service in Cloud Run'
    required: true
  project:
    description: 'GCP project'
    required: true
  region:
    description: 'GCP region'
    required: true
  service key:
    description: 'GCP service key with storage and run permissions'
    required: true
  cloud_sql:
    description: 'CloudSQL instance name'
    required: false
  env:
    description: 'Environment variables file'
    required: false
  min_instances:
    description: 'Minimum number of instance'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
